# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileDataRecorder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileDataRecorder

 pod 'Alamofire', '~> 5.2'
  pod "TTGSnackbar"
  pod 'MBProgressHUD'
  pod 'RealmSwift'

  target 'MobileDataRecorderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileDataRecorderUITests' do
    # Pods for testing
  end

end
